GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs/2

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "ConstructionTips",
    "author": "Joi",
    "url": "www.hihere.oi",
    "likes": 22,
    "userId": "5d3d847e42cb754f545d0684"
}

### 

PUT http://localhost:3003/api/blogs/5d3ca9158be4c9331cc1a368
Content-Type: application/json

{
    "title": "GardeningTips",
    "author": "Josh",
    "url": "www.hithere.io",
    "likes": 22
}

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hithere",
    "name": "Dani Boi",
    "password": "hi"
}